[domains]
members = [
    "plic",
    "syscall",
    "task",
    "vfs",
    "buf_uart",
    "buf_input",
    "cache_blk",
    "goldfish",
    "null",
    "random",
    "shadow_blk",
    "sshadow_blk",
    "uart16550",
    "virtio_mmio_block",
    "virtio_mmio_net",
    "virtio_mmio_input",
    "virtio_mmio_gpu",
    "devfs",
    "fatfs",
    "pipefs",
    "ramfs",
    "sysfs",
    "procfs",
    "fifo_scheduler",
    "random_scheduler",
    "logger",
    "xlogger",
    "net_stack",
    "domainfs",
    "vfs2",
    "loopback",
    "uart8250",
    "mem_block",
    "vf2_sd",
]

init_members = [
    "plic",
    "syscall",
    "task",
    "vfs",
    "buf_uart",
    "buf_input",
    "cache_blk",
    "goldfish",
    "null",
    "random",
    "shadow_blk",
    "uart16550",
    "virtio_mmio_block",
    "devfs",
    "fatfs",
    "pipefs",
    "ramfs",
    "sysfs",
    "procfs",
    "fifo_scheduler",
    "logger",
    "net_stack",
    "domainfs",
    "uart8250",
    "mem_block",
    "vf2_sd"
]

disk_members = [
    "sshadow_blk",
    "virtio_mmio_gpu",
    "virtio_mmio_input",
    "virtio_mmio_net",
    "random_scheduler",
    "xlogger",
    "vfs2",
    "loopback"
]

members_riscv64 = [
    "plic",
    "syscall",
    "task",
    "vfs",
    "buf_uart",
    "buf_input",
    "cache_blk",
    "goldfish",
    "null",
    "random",
    "shadow_blk",
    "sshadow_blk",
    "uart16550",
    "virtio_mmio_block",
    "virtio_mmio_net",
    "virtio_mmio_input",
    "virtio_mmio_gpu",
    "devfs",
    "fatfs",
    "pipefs",
    "ramfs",
    "sysfs",
    "procfs",
    "fifo_scheduler",
    "random_scheduler",
    "logger",
    "xlogger",
    "net_stack",
    "domainfs",
    "vfs2",
    "loopback",
    "uart8250",
    "mem_block",
    "vf2_sd",
]

init_members_riscv64 = [
    "plic",
    "syscall",
    "task",
    "vfs",
    "buf_uart",
    "buf_input",
    "cache_blk",
    "goldfish",
    "null",
    "random",
    "shadow_blk",
    "uart16550",
    "virtio_mmio_block",
    "devfs",
    "fatfs",
    "pipefs",
    "ramfs",
    "sysfs",
    "procfs",
    "fifo_scheduler",
    "logger",
    "net_stack",
    "domainfs",
    "uart8250",
    "mem_block",
    "vf2_sd"
]

disk_members_riscv64 = [
    "sshadow_blk",
    "virtio_mmio_gpu",
    "virtio_mmio_input",
    "virtio_mmio_net",
    "random_scheduler",
    "xlogger",
    "vfs2",
    "loopback"
]

members_x86_64 = [
    "syscall",
    "task",
    "vfs",
    "buf_uart",
    "buf_input",
    "cache_blk",
    "null",
    "random",
    "shadow_blk",
    "sshadow_blk",
    "apic",
    "local_apic",
    "io_apic",
    "hpet",
    "uart16550",
    "virtio_mmio_block",
    "virtio_mmio_net",
    "virtio_mmio_input",
    "virtio_mmio_gpu",
    "devfs",
    "fatfs",
    "pipefs",
    "ramfs",
    "sysfs",
    "procfs",
    "fifo_scheduler",
    "random_scheduler",
    "logger",
    "xlogger",
    "net_stack",
    "domainfs",
    "vfs2",
    "loopback",
    "mem_block"
]

init_members_x86_64 = [
    "syscall",
    "task",
    "vfs",
    "buf_uart",
    "buf_input",
    "cache_blk",
    "null",
    "random",
    "shadow_blk",
    "apic",
    "local_apic",
    "io_apic",
    "hpet",
    "uart16550",
    "virtio_mmio_block",
    "virtio_mmio_net",
    "virtio_mmio_input",
    "virtio_mmio_gpu",
    "devfs",
    "fatfs",
    "pipefs",
    "ramfs",
    "sysfs",
    "procfs",
    "fifo_scheduler",
    "logger",
    "net_stack",
    "domainfs",
    "mem_block"
]

disk_members_x86_64 = [
    "sshadow_blk",
    "virtio_mmio_gpu",
    "virtio_mmio_input",
    "virtio_mmio_net",
    "random_scheduler",
    "xlogger",
    "vfs2",
    "loopback"
]

members_plat_qemu_riscv = [
    "plic",
    "syscall",
    "task",
    "vfs",
    "buf_uart",
    "buf_input",
    "cache_blk",
    "goldfish",
    "null",
    "random",
    "shadow_blk",
    "sshadow_blk",
    "uart16550",
    "virtio_mmio_block",
    "virtio_mmio_net",
    "virtio_mmio_input",
    "virtio_mmio_gpu",
    "devfs",
    "fatfs",
    "pipefs",
    "ramfs",
    "sysfs",
    "procfs",
    "fifo_scheduler",
    "random_scheduler",
    "logger",
    "xlogger",
    "net_stack",
    "domainfs",
    "vfs2",
    "loopback",
    "mem_block"
]

init_members_plat_qemu_riscv = [
    "plic",
    "syscall",
    "task",
    "vfs",
    "buf_uart",
    "buf_input",
    "cache_blk",
    "goldfish",
    "null",
    "random",
    "shadow_blk",
    "uart16550",
    "virtio_mmio_block",
    "devfs",
    "fatfs",
    "pipefs",
    "ramfs",
    "sysfs",
    "procfs",
    "fifo_scheduler",
    "logger",
    "net_stack",
    "domainfs",
    "mem_block"
]

disk_members_plat_qemu_riscv = [
    "sshadow_blk",
    "virtio_mmio_gpu",
    "virtio_mmio_input",
    "virtio_mmio_net",
    "random_scheduler",
    "xlogger",
    "vfs2",
    "loopback"
]

members_plat_vf2 = [
    "plic",
    "syscall",
    "task",
    "vfs",
    "buf_uart",
    "buf_input",
    "cache_blk",
    "null",
    "random",
    "shadow_blk",
    "sshadow_blk",
    "uart8250",
    "devfs",
    "fatfs",
    "pipefs",
    "ramfs",
    "sysfs",
    "procfs",
    "fifo_scheduler",
    "random_scheduler",
    "logger",
    "xlogger",
    "net_stack",
    "domainfs",
    "vfs2",
    "loopback",
    "mem_block",
    "vf2_sd"
]

init_members_plat_vf2 = [
    "plic",
    "syscall",
    "task",
    "vfs",
    "buf_uart",
    "buf_input",
    "cache_blk",
    "null",
    "random",
    "shadow_blk",
    "devfs",
    "fatfs",
    "pipefs",
    "ramfs",
    "sysfs",
    "procfs",
    "fifo_scheduler",
    "logger",
    "net_stack",
    "domainfs",
    "uart8250",
    "mem_block",
    "vf2_sd"
]

disk_members_plat_vf2 = [
    "sshadow_blk",
    "random_scheduler",
    "xlogger",
    "vfs2",
    "loopback"
]

members_plat_qemu_x86_64 = [
    "syscall",
    "task",
    "vfs",
    "buf_uart",
    "buf_input",
    "cache_blk",
    "null",
    "random",
    "shadow_blk",
    "sshadow_blk",
    "uart16550",
    "virtio_mmio_block",
    "devfs",
    "fatfs",
    "pipefs",
    "ramfs",
    "sysfs",
    "procfs",
    "fifo_scheduler",
    "random_scheduler",
    "logger",
    "xlogger",
    "net_stack",
    "domainfs",
    "vfs2",
    "loopback",
    "mem_block"
]

init_members_plat_qemu_x86_64 = [
    "syscall",
    "task",
    "vfs",
    "buf_uart",
    "buf_input",
    "cache_blk",
    "null",
    "random",
    "shadow_blk",
    "uart16550",
    "virtio_mmio_block",
    "devfs",
    "fatfs",
    "pipefs",
    "ramfs",
    "sysfs",
    "procfs",
    "fifo_scheduler",
    "logger",
    "net_stack",
    "domainfs",
    "mem_block"
]

disk_members_plat_qemu_x86_64 = [
    "sshadow_blk",
    "random_scheduler",
    "xlogger",
    "vfs2",
    "loopback"
]